name: Feed Updater

# Runs every 2 hours
on:
  schedule:
    - cron: "0 */2 * * *" # Every 2 hours
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-feeds:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # Set explicit timeout

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Use current LTS version

      - name: Install dependencies
        run: npm install

      - name: Run feed updater
        env:
          MONGODB_CLUSTER_PASSWORD: ${{ secrets.MONGODB_CLUSTER_PASSWORD }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          GITHUB_JOB_START_TIME: ${{ env.GITHUB_RUN_ID }}
        run: |
          # Set start time for script to use
          export GITHUB_JOB_START_TIME=$(date +%s000)
          node --trace-warnings src/services/runFeedUpdates.js || {
            echo "Feed updater failed with exit code $?"
            exit 1
          }
